# Información de la aplicación
spring.application.name=backend-api-rest
spring.application.description=API REST de Calculadora con arquitectura DDD

# Configuración de base de datos (acceso desde fuera de Docker)
spring.datasource.url=jdbc:postgresql://localhost:5433/postgres
spring.datasource.username=postgres
spring.datasource.password=leon
spring.datasource.driver-class-name=org.postgresql.Driver

# Dialecto de Hibernate (recomendado para evitar errores)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Configuración del servidor
server.port=8085

# Configuración de SpringDoc / Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.doc-expansion=none
springdoc.default-produces-media-type=application/json
springdoc.swagger-ui.display-request-duration=true
springdoc.packagesToScan=com.challenge.backend_api_rest.interfaces.rest
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.cache.disabled=true
